title:          Eðlisfræði fyrir framhaldsskóla
author:         Matthias Harksen
email:          matthias.harksen@gmail.com

url: "https://mrharksen.github.io"

toc:
  enabled: true
  h_min: 1
  h_max: 3

favicon_path: /assets/gitbook/images/favicon.ico

# Build settings
remote_theme: sighingnow/jekyll-gitbook

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  chapters:
    output: true
    permalink: /:path/

ordered_collections:
  - posts
  - pages
  - chapters

plugins:
  - jekyll-remote-theme
  - jekyll-feed